name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make test
      run: make test
    - name: self-compile
      run: test/test_self_compile.sh ; test/test_self_compile.sh
